version: '3.9'

services:
  web:
    image: djan-psql
    restart: always
    build: ./base
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./base/:/base/
    ports:
      - "8000:8000"
    env_file:
      - ./base/base/.env.dev
    depends_on:
      - db

  db:
    image: postgres:14.8
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

    env_file:
      - ./base/base/.env.dev

    environment:
      - POSTGRES_DB=web_base
      - POSTGRES_USER=web_admin
      - POSTGRES_PASSWORD=admin

volumes:
  postgres_data:

