# Generated by Django 4.2.3 on 2023-07-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=100, verbose_name='название')),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Тестовая Модель',
            },
        ),
    ]
