# Generated by Django 4.2.3 on 2023-07-25 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_carmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
