# Generated by Django 4.2.3 on 2023-07-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_testmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name_plural': 'Тестовая Модель'},
        ),
    ]
